export const SET_LOADING_POKEMONS = "SET_LOADING_POKEMONS";
export const SET_POKEMON_DATA = "SET_POKEMON_DATA";
export const SET_POKEMON_DATA_ERROR = "SET_POKEMON_DATA_ERROR";
export const SET_POKEMONS_BY_TYPE = "SET_POKEMONs_BY_TYPE";

export const SET_LOADING_POKEMONS_BY_TYPE = "SET_LOADING_POKEMONS_BY_TYPE";
export const SET_POKEMON_DATA_ERROR_BY_TYPE = "SET_POKEMON_DATA_ERROR_BY_TYPE";